FROM python:3.9.7-alpine

ENV PYTHONUNBUFFERD=1
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

WORKDIR /django

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt